# -*- coding: utf-8 -*-
"""ColloborativeRecModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FfnajNsyiICxUE7Ljl55_wHuROPFC2W
"""

#created kmeans model

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
import pandas as pd

product_descriptions = pd.read_csv('product_descriptions.csv')

product_descriptions = product_descriptions.dropna()
product_descriptions.head()

product_descriptions1 = product_descriptions.head(500)
# product_descriptions1.iloc[:,1]

product_descriptions1["product_description"].head(10)

vectorizer = TfidfVectorizer(stop_words='english')
X1 = vectorizer.fit_transform(product_descriptions1["product_description"])
X1

X1

X=X1

kmeans = KMeans(n_clusters = 10, init = 'k-means++')
y_kmeans = kmeans.fit_predict(X)
plt.plot(y_kmeans, ".")
plt.show()

def print_cluster(i):
    print("Cluster %d:" % i),
    for ind in order_centroids[i, :10]:
        print(' %s' % terms[ind]),
    print

true_k = 10

model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1)
model.fit(X1)

print("Top terms per cluster:")
order_centroids = model.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names()
for i in range(true_k):
    print_cluster(i)

def show_recommendations(product):
    #print("Cluster ID:")
    Y = vectorizer.transform([product]) #put it in numbers
    prediction = model.predict(Y) #using those numbers, we find the nearby cluster
    #print(prediction)
    print_cluster(prediction[0])

show_recommendations("spray paint")

#testing the model

pd.read_csv('train.csv',encoding='latin-1')

from sklearn.metrics import classification_report

from sklearn.metrics import confusion_matrix